require 'user.launch'

require 'user.autocmds'
require 'user.options'
require 'user.keymaps'

spec 'user.colorscheme'
spec 'user.neogit'
spec 'user.mason'
spec 'user.vimlatex'
spec 'user.nvimtree'
spec 'user.treesitter'
spec 'user.lsp_config'
spec 'user.aerial'
spec 'user.illuminate'
spec 'user.breadcrumbs'
spec 'user.telescope'
spec 'user.indentguides'
spec 'user.marks'
spec 'user.rsi'
spec 'user.surround'
spec 'user.python_venv'
spec 'user.todo_comments'
spec 'user.project_manager'
spec 'user.trouble'
spec 'user.codeactions'
spec 'user.codeactions_preview'
spec 'user.lualine'
spec 'user.snippets'

require 'user.lazy'
